"use client";

import { Geist, Instrument_Serif } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import BackgroundLayoutContent from "./components/BackgroundLayoutContent";
import { usePathname } from "next/navigation";

export const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathName = usePathname();
  return (
    <html lang="en" className="">
      <body
        className={`${
          pathName === "/arch" ? "bg-[#0E0E0F]" : "bg-[#FAFAFB]"
        } antialiased relative`}
      >
        <div className="">
          <BackgroundLayoutContent />
          {/* Foreground content */}

          <div className={`relative z-10 mx-auto max-w-[1840px] text-black`}>
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
