import { Geist, Instrument_Serif } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import fullbg from "@/app/assets/svg/fullbg.svg";
import Header from "./components/Header";
import shape1 from "@/app/assets/svg/shape1.svg";
import shape2 from "@/app/assets/svg/shape2.svg";

export const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className={`bg-[#FAFAFB] antialiased relative`}>
        {/* Background image */}
        <div className="fixed inset-0 -z-10">
          <Image
            className="object-cover w-full h-full -scale-y-100"
            src={"https://res.cloudinary.com/dvaeb0mxy/image/upload/v1755705258/fullbg_crrpgn.svg"}
            alt="Background"
            fill
            priority
          />
        </div>
        <div className="absolute w-[400px] h-[400px] -top-20 right-0 min-[2500px]:w-[2000px] min-[2500px]:top-0 min-[2500px]:right-20">
          <Image
            className=" w-full h-full  object-fill"
            fill
            src={"https://res.cloudinary.com/dvaeb0mxy/image/upload/v1755705870/shape1_kkfg5l.svg"}
            alt="shape1"
            priority
          />
        </div>
        <div className=" absolute hidden min-[1000px]:block  w-[200px] h-[400px]  2xl:h-[600px]  md:top-60 xl:top-52  -left-5 min-[2500px]:hidden ">
          <Image
            className=" w-full h-full  object-fill"
            fill
            src={"https://res.cloudinary.com/dvaeb0mxy/image/upload/v1755705937/shape2_kaovqp.svg"}
            alt="shape2"
            priority
          />
        </div>
        {/* Foreground content */}
        <div className="relative z-10 mx-auto max-w-[1840px] text-black">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
