import { Geist, Instrument_Serif } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import fullbg from "@/app/assets/svg/fullbg.svg";
import Header from "./components/Header";
import shape1 from "@/app/assets/svg/shape1.svg";
import shape2 from "@/app/assets/svg/shape2.svg";
import { CldImage } from "next-cloudinary";
import BackgroundLayoutContent from "./components/BackgroundLayoutContent";

export const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className={`bg-[#0E0E0F] antialiased relative`}>
        <BackgroundLayoutContent />
        {/* Foreground content */}

        <div className={`relative z-10 mx-auto max-w-[1840px] text-black`}>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
